INSERT INTO job_master
  (company_key, entity_id, job_master_type, job_master_priority, job_master_status)
VALUES
;

/* GORO *//*
SELECT CONCAT("  (", company_key, ",'", id, "'", ",'PosRegisterClosure',", 1, ",'NUEVO'),") FROM erp_1001.erp_pos_register_closures WHERE NOT register_closure_done AND register_closure_exception IS NULL AND register_closure_date >= '2022-12-01' UNION ALL
SELECT CONCAT("  (", company_key, ",'", id, "'", ",'PosRegisterClosure',", 1, ",'NUEVO'),") FROM erp_1002.erp_pos_register_closures WHERE NOT register_closure_done AND register_closure_exception IS NULL AND register_closure_date >= '2022-12-01' UNION ALL
SELECT CONCAT("  (", company_key, ",'", id, "'", ",'PosRegisterClosure',", 1, ",'NUEVO'),") FROM erp_1003.erp_pos_register_closures WHERE NOT register_closure_done AND register_closure_exception IS NULL AND register_closure_date >= '2022-12-01' UNION ALL
SELECT CONCAT("  (", company_key, ",'", id, "'", ",'PosRegisterClosure',", 1, ",'NUEVO'),") FROM erp_1004.erp_pos_register_closures WHERE NOT register_closure_done AND register_closure_exception IS NULL AND register_closure_date >= '2022-12-01' UNION ALL
SELECT CONCAT("  (", company_key, ",'", id, "'", ",'PosRegisterClosure',", 1, ",'NUEVO'),") FROM erp_1005.erp_pos_register_closures WHERE NOT register_closure_done AND register_closure_exception IS NULL AND register_closure_date >= '2022-12-01' UNION ALL
SELECT CONCAT("  (", company_key, ",'", id, "'", ",'PosRegisterClosure',", 1, ",'NUEVO'),") FROM erp_1006.erp_pos_register_closures WHERE NOT register_closure_done AND register_closure_exception IS NULL AND register_closure_date >= '2022-12-01' UNION ALL
SELECT CONCAT("  (", company_key, ",'", id, "'", ",'PosRegisterClosure',", 1, ",'NUEVO'),") FROM erp_1007.erp_pos_register_closures WHERE NOT register_closure_done AND register_closure_exception IS NULL AND register_closure_date >= '2022-12-01' UNION ALL
SELECT CONCAT("  (", company_key, ",'", id, "'", ",'PosRegisterClosure',", 1, ",'NUEVO'),") FROM erp_1008.erp_pos_register_closures WHERE NOT register_closure_done AND register_closure_exception IS NULL AND register_closure_date >= '2022-12-01' UNION ALL
SELECT CONCAT("  (", company_key, ",'", id, "'", ",'PosRegisterClosure',", 1, ",'NUEVO'),") FROM erp_1009.erp_pos_register_closures WHERE NOT register_closure_done AND register_closure_exception IS NULL AND register_closure_date >= '2022-12-01' UNION ALL
SELECT CONCAT("  (", company_key, ",'", id, "'", ",'PosRegisterClosure',", 1, ",'NUEVO'),") FROM erp_1010.erp_pos_register_closures WHERE NOT register_closure_done AND register_closure_exception IS NULL AND register_closure_date >= '2022-12-01' UNION ALL
SELECT CONCAT("  (", company_key, ",'", id, "'", ",'PosRegisterClosure',", 1, ",'NUEVO'),") FROM erp_1011.erp_pos_register_closures WHERE NOT register_closure_done AND register_closure_exception IS NULL AND register_closure_date >= '2022-12-01' UNION ALL
SELECT CONCAT("  (", company_key, ",'", id, "'", ",'PosRegisterClosure',", 1, ",'NUEVO'),") FROM erp_1012.erp_pos_register_closures WHERE NOT register_closure_done AND register_closure_exception IS NULL AND register_closure_date >= '2022-12-01' UNION ALL
SELECT CONCAT("  (", company_key, ",'", id, "'", ",'PosRegisterClosure',", 1, ",'NUEVO'),") FROM erp_1013.erp_pos_register_closures WHERE NOT register_closure_done AND register_closure_exception IS NULL AND register_closure_date >= '2022-12-01' UNION ALL
SELECT CONCAT("  (", company_key, ",'", id, "'", ",'PosRegisterClosure',", 1, ",'NUEVO'),") FROM erp_1014.erp_pos_register_closures WHERE NOT register_closure_done AND register_closure_exception IS NULL AND register_closure_date >= '2022-12-01' UNION ALL
SELECT CONCAT("  (", company_key, ",'", id, "'", ",'PosRegisterClosure',", 1, ",'NUEVO'),") FROM erp_1015.erp_pos_register_closures WHERE NOT register_closure_done AND register_closure_exception IS NULL AND register_closure_date >= '2022-12-01'
;*/

/* SCORPION *//*
SELECT CONCAT("(", company_key, ",'", id, "'", ",'PosRegisterClosure',", 1, ",'NUEVO'),") FROM erp_1016.erp_pos_register_closures WHERE NOT register_closure_done AND register_closure_exception IS NULL AND register_closure_date >= '2022-12-01' UNION ALL
SELECT CONCAT("(", company_key, ",'", id, "'", ",'PosRegisterClosure',", 1, ",'NUEVO'),") FROM erp_1017.erp_pos_register_closures WHERE NOT register_closure_done AND register_closure_exception IS NULL AND register_closure_date >= '2022-12-01' UNION ALL
SELECT CONCAT("(", company_key, ",'", id, "'", ",'PosRegisterClosure',", 1, ",'NUEVO'),") FROM erp_1018.erp_pos_register_closures WHERE NOT register_closure_done AND register_closure_exception IS NULL AND register_closure_date >= '2022-12-01' UNION ALL
SELECT CONCAT("(", company_key, ",'", id, "'", ",'PosRegisterClosure',", 1, ",'NUEVO'),") FROM erp_1019.erp_pos_register_closures WHERE NOT register_closure_done AND register_closure_exception IS NULL AND register_closure_date >= '2022-12-01' UNION ALL
SELECT CONCAT("(", company_key, ",'", id, "'", ",'PosRegisterClosure',", 1, ",'NUEVO'),") FROM erp_1020.erp_pos_register_closures WHERE NOT register_closure_done AND register_closure_exception IS NULL AND register_closure_date >= '2022-12-01' UNION ALL
SELECT CONCAT("(", company_key, ",'", id, "'", ",'PosRegisterClosure',", 1, ",'NUEVO'),") FROM erp_1021.erp_pos_register_closures WHERE NOT register_closure_done AND register_closure_exception IS NULL AND register_closure_date >= '2022-12-01' UNION ALL
SELECT CONCAT("(", company_key, ",'", id, "'", ",'PosRegisterClosure',", 1, ",'NUEVO'),") FROM erp_1022.erp_pos_register_closures WHERE NOT register_closure_done AND register_closure_exception IS NULL AND register_closure_date >= '2022-12-01' UNION ALL
SELECT CONCAT("(", company_key, ",'", id, "'", ",'PosRegisterClosure',", 1, ",'NUEVO'),") FROM erp_1023.erp_pos_register_closures WHERE NOT register_closure_done AND register_closure_exception IS NULL AND register_closure_date >= '2022-12-01' UNION ALL
SELECT CONCAT("(", company_key, ",'", id, "'", ",'PosRegisterClosure',", 1, ",'NUEVO'),") FROM erp_1024.erp_pos_register_closures WHERE NOT register_closure_done AND register_closure_exception IS NULL AND register_closure_date >= '2022-12-01' UNION ALL
SELECT CONCAT("(", company_key, ",'", id, "'", ",'PosRegisterClosure',", 1, ",'NUEVO'),") FROM erp_1025.erp_pos_register_closures WHERE NOT register_closure_done AND register_closure_exception IS NULL AND register_closure_date >= '2022-12-01' UNION ALL
SELECT CONCAT("(", company_key, ",'", id, "'", ",'PosRegisterClosure',", 1, ",'NUEVO'),") FROM erp_1026.erp_pos_register_closures WHERE NOT register_closure_done AND register_closure_exception IS NULL AND register_closure_date >= '2022-12-01' UNION ALL
SELECT CONCAT("(", company_key, ",'", id, "'", ",'PosRegisterClosure',", 1, ",'NUEVO'),") FROM erp_1027.erp_pos_register_closures WHERE NOT register_closure_done AND register_closure_exception IS NULL AND register_closure_date >= '2022-12-01' UNION ALL
SELECT CONCAT("(", company_key, ",'", id, "'", ",'PosRegisterClosure',", 1, ",'NUEVO'),") FROM erp_1028.erp_pos_register_closures WHERE NOT register_closure_done AND register_closure_exception IS NULL AND register_closure_date >= '2022-12-01' UNION ALL
SELECT CONCAT("(", company_key, ",'", id, "'", ",'PosRegisterClosure',", 1, ",'NUEVO'),") FROM erp_1029.erp_pos_register_closures WHERE NOT register_closure_done AND register_closure_exception IS NULL AND register_closure_date >= '2022-12-01' UNION ALL
SELECT CONCAT("(", company_key, ",'", id, "'", ",'PosRegisterClosure',", 1, ",'NUEVO'),") FROM erp_1030.erp_pos_register_closures WHERE NOT register_closure_done AND register_closure_exception IS NULL AND register_closure_date >= '2022-12-01'
;*/

/* SINDEL *//*
SELECT CONCAT("(", company_key, ",'", id, "'", ",'PosRegisterClosure',", 1, ",'NUEVO'),") FROM erp_1031.erp_pos_register_closures WHERE NOT register_closure_done AND register_closure_exception IS NULL AND register_closure_date >= '2022-12-01' UNION ALL
SELECT CONCAT("(", company_key, ",'", id, "'", ",'PosRegisterClosure',", 1, ",'NUEVO'),") FROM erp_1032.erp_pos_register_closures WHERE NOT register_closure_done AND register_closure_exception IS NULL AND register_closure_date >= '2022-12-01' UNION ALL
SELECT CONCAT("(", company_key, ",'", id, "'", ",'PosRegisterClosure',", 1, ",'NUEVO'),") FROM erp_1033.erp_pos_register_closures WHERE NOT register_closure_done AND register_closure_exception IS NULL AND register_closure_date >= '2022-12-01' UNION ALL
SELECT CONCAT("(", company_key, ",'", id, "'", ",'PosRegisterClosure',", 1, ",'NUEVO'),") FROM erp_1034.erp_pos_register_closures WHERE NOT register_closure_done AND register_closure_exception IS NULL AND register_closure_date >= '2022-12-01' UNION ALL
SELECT CONCAT("(", company_key, ",'", id, "'", ",'PosRegisterClosure',", 1, ",'NUEVO'),") FROM erp_1035.erp_pos_register_closures WHERE NOT register_closure_done AND register_closure_exception IS NULL AND register_closure_date >= '2022-12-01' UNION ALL
SELECT CONCAT("(", company_key, ",'", id, "'", ",'PosRegisterClosure',", 1, ",'NUEVO'),") FROM erp_1036.erp_pos_register_closures WHERE NOT register_closure_done AND register_closure_exception IS NULL AND register_closure_date >= '2022-12-01' UNION ALL
SELECT CONCAT("(", company_key, ",'", id, "'", ",'PosRegisterClosure',", 1, ",'NUEVO'),") FROM erp_1037.erp_pos_register_closures WHERE NOT register_closure_done AND register_closure_exception IS NULL AND register_closure_date >= '2022-12-01' UNION ALL
SELECT CONCAT("(", company_key, ",'", id, "'", ",'PosRegisterClosure',", 1, ",'NUEVO'),") FROM erp_1038.erp_pos_register_closures WHERE NOT register_closure_done AND register_closure_exception IS NULL AND register_closure_date >= '2022-12-01' UNION ALL
SELECT CONCAT("(", company_key, ",'", id, "'", ",'PosRegisterClosure',", 1, ",'NUEVO'),") FROM erp_1039.erp_pos_register_closures WHERE NOT register_closure_done AND register_closure_exception IS NULL AND register_closure_date >= '2022-12-01' UNION ALL
SELECT CONCAT("(", company_key, ",'", id, "'", ",'PosRegisterClosure',", 1, ",'NUEVO'),") FROM erp_1040.erp_pos_register_closures WHERE NOT register_closure_done AND register_closure_exception IS NULL AND register_closure_date >= '2022-12-01' UNION ALL
SELECT CONCAT("(", company_key, ",'", id, "'", ",'PosRegisterClosure',", 1, ",'NUEVO'),") FROM erp_1041.erp_pos_register_closures WHERE NOT register_closure_done AND register_closure_exception IS NULL AND register_closure_date >= '2022-12-01' UNION ALL
SELECT CONCAT("(", company_key, ",'", id, "'", ",'PosRegisterClosure',", 1, ",'NUEVO'),") FROM erp_1042.erp_pos_register_closures WHERE NOT register_closure_done AND register_closure_exception IS NULL AND register_closure_date >= '2022-12-01' UNION ALL
SELECT CONCAT("(", company_key, ",'", id, "'", ",'PosRegisterClosure',", 1, ",'NUEVO'),") FROM erp_1043.erp_pos_register_closures WHERE NOT register_closure_done AND register_closure_exception IS NULL AND register_closure_date >= '2022-12-01' UNION ALL
SELECT CONCAT("(", company_key, ",'", id, "'", ",'PosRegisterClosure',", 1, ",'NUEVO'),") FROM erp_1044.erp_pos_register_closures WHERE NOT register_closure_done AND register_closure_exception IS NULL AND register_closure_date >= '2022-12-01' UNION ALL
SELECT CONCAT("(", company_key, ",'", id, "'", ",'PosRegisterClosure',", 1, ",'NUEVO'),") FROM erp_1045.erp_pos_register_closures WHERE NOT register_closure_done AND register_closure_exception IS NULL AND register_closure_date >= '2022-12-01'
;*/

/* BARAKA *//*
SELECT CONCAT("  (", company_key, ",'", id, "'", ",'PosRegisterClosure',", 1, ",'NUEVO'),") FROM erp_1046.erp_pos_register_closures WHERE NOT register_closure_done AND register_closure_exception IS NULL AND register_closure_date >= '2022-12-01' UNION ALL
SELECT CONCAT("  (", company_key, ",'", id, "'", ",'PosRegisterClosure',", 1, ",'NUEVO'),") FROM erp_1047.erp_pos_register_closures WHERE NOT register_closure_done AND register_closure_exception IS NULL AND register_closure_date >= '2022-12-01' UNION ALL
SELECT CONCAT("  (", company_key, ",'", id, "'", ",'PosRegisterClosure',", 1, ",'NUEVO'),") FROM erp_1048.erp_pos_register_closures WHERE NOT register_closure_done AND register_closure_exception IS NULL AND register_closure_date >= '2022-12-01' UNION ALL
SELECT CONCAT("  (", company_key, ",'", id, "'", ",'PosRegisterClosure',", 1, ",'NUEVO'),") FROM erp_1049.erp_pos_register_closures WHERE NOT register_closure_done AND register_closure_exception IS NULL AND register_closure_date >= '2022-12-01' UNION ALL
SELECT CONCAT("  (", company_key, ",'", id, "'", ",'PosRegisterClosure',", 1, ",'NUEVO'),") FROM erp_1050.erp_pos_register_closures WHERE NOT register_closure_done AND register_closure_exception IS NULL AND register_closure_date >= '2022-12-01' UNION ALL
SELECT CONCAT("  (", company_key, ",'", id, "'", ",'PosRegisterClosure',", 1, ",'NUEVO'),") FROM erp_1051.erp_pos_register_closures WHERE NOT register_closure_done AND register_closure_exception IS NULL AND register_closure_date >= '2022-12-01' UNION ALL
SELECT CONCAT("  (", company_key, ",'", id, "'", ",'PosRegisterClosure',", 1, ",'NUEVO'),") FROM erp_1052.erp_pos_register_closures WHERE NOT register_closure_done AND register_closure_exception IS NULL AND register_closure_date >= '2022-12-01' UNION ALL
SELECT CONCAT("  (", company_key, ",'", id, "'", ",'PosRegisterClosure',", 1, ",'NUEVO'),") FROM erp_1053.erp_pos_register_closures WHERE NOT register_closure_done AND register_closure_exception IS NULL AND register_closure_date >= '2022-12-01' UNION ALL
SELECT CONCAT("  (", company_key, ",'", id, "'", ",'PosRegisterClosure',", 1, ",'NUEVO'),") FROM erp_1054.erp_pos_register_closures WHERE NOT register_closure_done AND register_closure_exception IS NULL AND register_closure_date >= '2022-12-01' UNION ALL
SELECT CONCAT("  (", company_key, ",'", id, "'", ",'PosRegisterClosure',", 1, ",'NUEVO'),") FROM erp_1055.erp_pos_register_closures WHERE NOT register_closure_done AND register_closure_exception IS NULL AND register_closure_date >= '2022-12-01' UNION ALL
SELECT CONCAT("  (", company_key, ",'", id, "'", ",'PosRegisterClosure',", 1, ",'NUEVO'),") FROM erp_1056.erp_pos_register_closures WHERE NOT register_closure_done AND register_closure_exception IS NULL AND register_closure_date >= '2022-12-01' UNION ALL
SELECT CONCAT("  (", company_key, ",'", id, "'", ",'PosRegisterClosure',", 1, ",'NUEVO'),") FROM erp_1057.erp_pos_register_closures WHERE NOT register_closure_done AND register_closure_exception IS NULL AND register_closure_date >= '2022-12-01' UNION ALL
SELECT CONCAT("  (", company_key, ",'", id, "'", ",'PosRegisterClosure',", 1, ",'NUEVO'),") FROM erp_1058.erp_pos_register_closures WHERE NOT register_closure_done AND register_closure_exception IS NULL AND register_closure_date >= '2022-12-01' UNION ALL
SELECT CONCAT("  (", company_key, ",'", id, "'", ",'PosRegisterClosure',", 1, ",'NUEVO'),") FROM erp_1059.erp_pos_register_closures WHERE NOT register_closure_done AND register_closure_exception IS NULL AND register_closure_date >= '2022-12-01' UNION ALL
SELECT CONCAT("  (", company_key, ",'", id, "'", ",'PosRegisterClosure',", 1, ",'NUEVO'),") FROM erp_1060.erp_pos_register_closures WHERE NOT register_closure_done AND register_closure_exception IS NULL AND register_closure_date >= '2022-12-01'
;*/

/* JADE *//*
SELECT CONCAT("  (", company_key, ",'", id, "'", ",'PosRegisterClosure',", 1, ",'NUEVO'),") FROM erp_1061.erp_pos_register_closures WHERE NOT register_closure_done AND register_closure_exception IS NULL AND register_closure_date >= '2022-12-01' UNION ALL
SELECT CONCAT("  (", company_key, ",'", id, "'", ",'PosRegisterClosure',", 1, ",'NUEVO'),") FROM erp_1063.erp_pos_register_closures WHERE NOT register_closure_done AND register_closure_exception IS NULL AND register_closure_date >= '2022-12-01' UNION ALL
SELECT CONCAT("  (", company_key, ",'", id, "'", ",'PosRegisterClosure',", 1, ",'NUEVO'),") FROM erp_1064.erp_pos_register_closures WHERE NOT register_closure_done AND register_closure_exception IS NULL AND register_closure_date >= '2022-12-01' UNION ALL
SELECT CONCAT("  (", company_key, ",'", id, "'", ",'PosRegisterClosure',", 1, ",'NUEVO'),") FROM erp_1065.erp_pos_register_closures WHERE NOT register_closure_done AND register_closure_exception IS NULL AND register_closure_date >= '2022-12-01' UNION ALL
SELECT CONCAT("  (", company_key, ",'", id, "'", ",'PosRegisterClosure',", 1, ",'NUEVO'),") FROM erp_1066.erp_pos_register_closures WHERE NOT register_closure_done AND register_closure_exception IS NULL AND register_closure_date >= '2022-12-01' UNION ALL
SELECT CONCAT("  (", company_key, ",'", id, "'", ",'PosRegisterClosure',", 1, ",'NUEVO'),") FROM erp_1062.erp_pos_register_closures WHERE NOT register_closure_done AND register_closure_exception IS NULL AND register_closure_date >= '2022-12-01' UNION ALL
SELECT CONCAT("  (", company_key, ",'", id, "'", ",'PosRegisterClosure',", 1, ",'NUEVO'),") FROM erp_1067.erp_pos_register_closures WHERE NOT register_closure_done AND register_closure_exception IS NULL AND register_closure_date >= '2022-12-01' UNION ALL
SELECT CONCAT("  (", company_key, ",'", id, "'", ",'PosRegisterClosure',", 1, ",'NUEVO'),") FROM erp_1068.erp_pos_register_closures WHERE NOT register_closure_done AND register_closure_exception IS NULL AND register_closure_date >= '2022-12-01' UNION ALL
SELECT CONCAT("  (", company_key, ",'", id, "'", ",'PosRegisterClosure',", 1, ",'NUEVO'),") FROM erp_1091.erp_pos_register_closures WHERE NOT register_closure_done AND register_closure_exception IS NULL AND register_closure_date >= '2022-12-01' UNION ALL
SELECT CONCAT("  (", company_key, ",'", id, "'", ",'PosRegisterClosure',", 1, ",'NUEVO'),") FROM erp_1092.erp_pos_register_closures WHERE NOT register_closure_done AND register_closure_exception IS NULL AND register_closure_date >= '2022-12-01' UNION ALL
SELECT CONCAT("  (", company_key, ",'", id, "'", ",'PosRegisterClosure',", 1, ",'NUEVO'),") FROM erp_1093.erp_pos_register_closures WHERE NOT register_closure_done AND register_closure_exception IS NULL AND register_closure_date >= '2022-12-01' UNION ALL
SELECT CONCAT("  (", company_key, ",'", id, "'", ",'PosRegisterClosure',", 1, ",'NUEVO'),") FROM erp_1094.erp_pos_register_closures WHERE NOT register_closure_done AND register_closure_exception IS NULL AND register_closure_date >= '2022-12-01' UNION ALL
SELECT CONCAT("  (", company_key, ",'", id, "'", ",'PosRegisterClosure',", 1, ",'NUEVO'),") FROM erp_1095.erp_pos_register_closures WHERE NOT register_closure_done AND register_closure_exception IS NULL AND register_closure_date >= '2022-12-01' UNION ALL
SELECT CONCAT("  (", company_key, ",'", id, "'", ",'PosRegisterClosure',", 1, ",'NUEVO'),") FROM erp_1096.erp_pos_register_closures WHERE NOT register_closure_done AND register_closure_exception IS NULL AND register_closure_date >= '2022-12-01' UNION ALL
SELECT CONCAT("  (", company_key, ",'", id, "'", ",'PosRegisterClosure',", 1, ",'NUEVO'),") FROM erp_1097.erp_pos_register_closures WHERE NOT register_closure_done AND register_closure_exception IS NULL AND register_closure_date >= '2022-12-01'
;*/

/* FROST *//*
SELECT CONCAT("  (", company_key, ",'", id, "'", ",'PosRegisterClosure',", 1, ",'NUEVO'),") FROM erp_1098.erp_pos_register_closures WHERE NOT register_closure_done AND register_closure_exception IS NULL AND register_closure_date >= '2022-12-01' UNION ALL
SELECT CONCAT("  (", company_key, ",'", id, "'", ",'PosRegisterClosure',", 1, ",'NUEVO'),") FROM erp_1099.erp_pos_register_closures WHERE NOT register_closure_done AND register_closure_exception IS NULL AND register_closure_date >= '2022-12-01' UNION ALL
SELECT CONCAT("  (", company_key, ",'", id, "'", ",'PosRegisterClosure',", 1, ",'NUEVO'),") FROM erp_1100.erp_pos_register_closures WHERE NOT register_closure_done AND register_closure_exception IS NULL AND register_closure_date >= '2022-12-01' UNION ALL
SELECT CONCAT("  (", company_key, ",'", id, "'", ",'PosRegisterClosure',", 1, ",'NUEVO'),") FROM erp_1101.erp_pos_register_closures WHERE NOT register_closure_done AND register_closure_exception IS NULL AND register_closure_date >= '2022-12-01' UNION ALL
SELECT CONCAT("  (", company_key, ",'", id, "'", ",'PosRegisterClosure',", 1, ",'NUEVO'),") FROM erp_1105.erp_pos_register_closures WHERE NOT register_closure_done AND register_closure_exception IS NULL AND register_closure_date >= '2022-12-01' UNION ALL
SELECT CONCAT("  (", company_key, ",'", id, "'", ",'PosRegisterClosure',", 1, ",'NUEVO'),") FROM erp_1106.erp_pos_register_closures WHERE NOT register_closure_done AND register_closure_exception IS NULL AND register_closure_date >= '2022-12-01' UNION ALL
SELECT CONCAT("  (", company_key, ",'", id, "'", ",'PosRegisterClosure',", 1, ",'NUEVO'),") FROM erp_1107.erp_pos_register_closures WHERE NOT register_closure_done AND register_closure_exception IS NULL AND register_closure_date >= '2022-12-01' UNION ALL
SELECT CONCAT("  (", company_key, ",'", id, "'", ",'PosRegisterClosure',", 1, ",'NUEVO'),") FROM erp_1111.erp_pos_register_closures WHERE NOT register_closure_done AND register_closure_exception IS NULL AND register_closure_date >= '2022-12-01' UNION ALL
SELECT CONCAT("  (", company_key, ",'", id, "'", ",'PosRegisterClosure',", 1, ",'NUEVO'),") FROM erp_1112.erp_pos_register_closures WHERE NOT register_closure_done AND register_closure_exception IS NULL AND register_closure_date >= '2022-12-01' UNION ALL
SELECT CONCAT("  (", company_key, ",'", id, "'", ",'PosRegisterClosure',", 1, ",'NUEVO'),") FROM erp_1113.erp_pos_register_closures WHERE NOT register_closure_done AND register_closure_exception IS NULL AND register_closure_date >= '2022-12-01' UNION ALL
SELECT CONCAT("  (", company_key, ",'", id, "'", ",'PosRegisterClosure',", 1, ",'NUEVO'),") FROM erp_1114.erp_pos_register_closures WHERE NOT register_closure_done AND register_closure_exception IS NULL AND register_closure_date >= '2022-12-01' UNION ALL
SELECT CONCAT("  (", company_key, ",'", id, "'", ",'PosRegisterClosure',", 1, ",'NUEVO'),") FROM erp_1117.erp_pos_register_closures WHERE NOT register_closure_done AND register_closure_exception IS NULL AND register_closure_date >= '2022-12-01' UNION ALL
SELECT CONCAT("  (", company_key, ",'", id, "'", ",'PosRegisterClosure',", 1, ",'NUEVO'),") FROM erp_1118.erp_pos_register_closures WHERE NOT register_closure_done AND register_closure_exception IS NULL AND register_closure_date >= '2022-12-01' UNION ALL
SELECT CONCAT("  (", company_key, ",'", id, "'", ",'PosRegisterClosure',", 1, ",'NUEVO'),") FROM erp_1119.erp_pos_register_closures WHERE NOT register_closure_done AND register_closure_exception IS NULL AND register_closure_date >= '2022-12-01' UNION ALL
SELECT CONCAT("  (", company_key, ",'", id, "'", ",'PosRegisterClosure',", 1, ",'NUEVO'),") FROM erp_1120.erp_pos_register_closures WHERE NOT register_closure_done AND register_closure_exception IS NULL AND register_closure_date >= '2022-12-01'
;*/

/* KIRA *//*
SELECT CONCAT("(", company_key, ",'", id, "'", ",'PosRegisterClosure',", 1, ",'NUEVO'),") FROM erp_1121.erp_pos_register_closures WHERE NOT register_closure_done AND register_closure_exception IS NULL AND register_closure_date >= '2022-12-01' UNION ALL
SELECT CONCAT("(", company_key, ",'", id, "'", ",'PosRegisterClosure',", 1, ",'NUEVO'),") FROM erp_1122.erp_pos_register_closures WHERE NOT register_closure_done AND register_closure_exception IS NULL AND register_closure_date >= '2022-12-01' UNION ALL
SELECT CONCAT("(", company_key, ",'", id, "'", ",'PosRegisterClosure',", 1, ",'NUEVO'),") FROM erp_1134.erp_pos_register_closures WHERE NOT register_closure_done AND register_closure_exception IS NULL AND register_closure_date >= '2022-12-01' UNION ALL
SELECT CONCAT("(", company_key, ",'", id, "'", ",'PosRegisterClosure',", 1, ",'NUEVO'),") FROM erp_1135.erp_pos_register_closures WHERE NOT register_closure_done AND register_closure_exception IS NULL AND register_closure_date >= '2022-12-01' UNION ALL
SELECT CONCAT("(", company_key, ",'", id, "'", ",'PosRegisterClosure',", 1, ",'NUEVO'),") FROM erp_1123.erp_pos_register_closures WHERE NOT register_closure_done AND register_closure_exception IS NULL AND register_closure_date >= '2022-12-01' UNION ALL
SELECT CONCAT("(", company_key, ",'", id, "'", ",'PosRegisterClosure',", 1, ",'NUEVO'),") FROM erp_1127.erp_pos_register_closures WHERE NOT register_closure_done AND register_closure_exception IS NULL AND register_closure_date >= '2022-12-01' UNION ALL
SELECT CONCAT("(", company_key, ",'", id, "'", ",'PosRegisterClosure',", 1, ",'NUEVO'),") FROM erp_1129.erp_pos_register_closures WHERE NOT register_closure_done AND register_closure_exception IS NULL AND register_closure_date >= '2022-12-01' UNION ALL
SELECT CONCAT("(", company_key, ",'", id, "'", ",'PosRegisterClosure',", 1, ",'NUEVO'),") FROM erp_1124.erp_pos_register_closures WHERE NOT register_closure_done AND register_closure_exception IS NULL AND register_closure_date >= '2022-12-01' UNION ALL
SELECT CONCAT("(", company_key, ",'", id, "'", ",'PosRegisterClosure',", 1, ",'NUEVO'),") FROM erp_1130.erp_pos_register_closures WHERE NOT register_closure_done AND register_closure_exception IS NULL AND register_closure_date >= '2022-12-01' UNION ALL
SELECT CONCAT("(", company_key, ",'", id, "'", ",'PosRegisterClosure',", 1, ",'NUEVO'),") FROM erp_1125.erp_pos_register_closures WHERE NOT register_closure_done AND register_closure_exception IS NULL AND register_closure_date >= '2022-12-01' UNION ALL
SELECT CONCAT("(", company_key, ",'", id, "'", ",'PosRegisterClosure',", 1, ",'NUEVO'),") FROM erp_1132.erp_pos_register_closures WHERE NOT register_closure_done AND register_closure_exception IS NULL AND register_closure_date >= '2022-12-01' UNION ALL
SELECT CONCAT("(", company_key, ",'", id, "'", ",'PosRegisterClosure',", 1, ",'NUEVO'),") FROM erp_1126.erp_pos_register_closures WHERE NOT register_closure_done AND register_closure_exception IS NULL AND register_closure_date >= '2022-12-01' UNION ALL
SELECT CONCAT("(", company_key, ",'", id, "'", ",'PosRegisterClosure',", 1, ",'NUEVO'),") FROM erp_1133.erp_pos_register_closures WHERE NOT register_closure_done AND register_closure_exception IS NULL AND register_closure_date >= '2022-12-01' UNION ALL
SELECT CONCAT("(", company_key, ",'", id, "'", ",'PosRegisterClosure',", 1, ",'NUEVO'),") FROM erp_1128.erp_pos_register_closures WHERE NOT register_closure_done AND register_closure_exception IS NULL AND register_closure_date >= '2022-12-01' UNION ALL
SELECT CONCAT("(", company_key, ",'", id, "'", ",'PosRegisterClosure',", 1, ",'NUEVO'),") FROM erp_1131.erp_pos_register_closures WHERE NOT register_closure_done AND register_closure_exception IS NULL AND register_closure_date >= '2022-12-01'
;*/
